### ISSUE TITLE
Draw DFD

### ISSUE THREAD

**Issue by aalexsm** [warkosanta/WeRec-specs#12]

**Comment by zhurbeySA** [comment]
![Image](https://user-images.githubusercontent.com/44731679/193103196-faa000fa-8793-4d66-b73a-cba13fd7d16e.png)

**Comment by zhurbeySA** [comment]
https://drive.google.com/file/d/1z90cyQ4Z6frVeflYAPK4cC4OjxLZamvk/view?usp=sharing
