### ISSUE TITLE
Presentation for ASD Task 3

### ISSUE THREAD

**Issue by aalexsm** [warkosanta/WeRec-specs#6]
- [x] Add description of Misha in wiki
- [x] Add description of Svetlana in wiki
- [x] Svetlana VP 
- [x] Prototype
- [x] Story map
- [x] Add folders in repo for Misha and Svetlana
- [x] Fill the glossary

**Comment by warkosanta** [comment]
@aalexsm miss boss, I think jobs map for each persona is redundant, feels like value proposition canvas is enough

**Comment by aalexsm** [comment]
@warkosanta forgot they were optional. np, the less to do the better :'-)

**Comment by warkosanta** [comment]
@MahmoudHossameldin could you please enrich description of Misha, give him more personality, maybe with some user stories idk

**Comment by aalexsm** [comment]
https://docs.google.com/presentation/d/1JwwdY_b_AsNY6H0bPKh_HAnzB75F3z8ghbRwePTHgxQ/edit?usp=sharing
